
services:
  # Our PostgreSQL Database
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: mydb


  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
